name: CI/CD Pipeline for Ionic App

on:
  push:
    branches:
      - main  # Déclenchement sur des push vers la branche principale (ou master)

jobs:
  # Job pour l'intégration continue (tests, linting)
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.9.0'  # Version de Node.js à utiliser

    - name: Install dependencies
      run: |
        npm install  # Installer les dépendances du projet

    - name: Lint code
      run: |
        npm run lint  # Lancer l'analyse statique du code (linting)

    - name: Run tests
      run: |
        npm run test -- --watch=false --browsers=ChromeHeadless  # Exécuter les tests unitaires (si configurés)

  # Job pour la construction de l'application
  build-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.9.0'

    - name: Install dependencies
      run: |
        npm install

    - name: Build the Ionic app
      run: |
        ionic build --prod  # Construire l'application pour la production

  # Job pour le déploiement
  deploy:
    runs-on: ubuntu-latest
    needs: build-app  # Ce job dépend de la réussite de la tâche build-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.9.0'

    - name: Install dependencies
      run: |
        npm install

    - name: Deploy the app
      run: |
        # Exemple pour déployer sur un serveur via SSH (remplacez par votre propre méthode de déploiement)
        scp -r ./www/* username@your-server:/path/to/deployment/directory

        # Si vous utilisez un service comme Firebase Hosting, Vercel ou Netlify, vous pouvez utiliser leurs CLI pour déployer
        # Exemple avec Firebase:
        # firebase deploy --token $FIREBASE_AUTH_TOKEN
